{% raw %}---
- name: check mandatory parameters
  fail: msg="db_user, db_name, db_password and db_version parameters are not defined"
  when: db_user is not defined or db_name is not defined or db_password is not defined or db_version is not defined

# here we need to pass the LANG env variable otherwise the template0 will be created with
#  another locale
- name: install necessary packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libpq-dev
    - postgresql-{{ db_version }}
    - python-psycopg2
  environment:
    LANG: 'it_IT.UTF-8'

- name: create database
  su: yes
  su_user: postgres
  postgresql_db:
      name="{{ db_name }}"
      encoding='UTF-8'
      lc_collate='it_IT.UTF-8'
      lc_ctype='it_IT.UTF-8'
      template='template0'

# https://groups.google.com/forum/#!topic/ansible-project/IknBo5QvJXQ
- name: create database user {% if development is defined %}(development mode){% endif %}
  su: yes
  su_user: postgres
  postgresql_user:
      db="{{ db_name }}"
      user="{{ db_user }}"
      password="{{ db_password }}"
      role_attr_flags={% if development is not defined %}NO{% endif %}CREATEDB,NOSUPERUSER

- name: grant privileges to user [DEVELOPMENT ENABLED]
  su: yes
  su_user: postgres
  postgresql_db:
    name="{{ db_name }}"
    owner="{{ db_user }}"
  when: development is defined

- service: name=postgresql state=started
{% endraw %}
